# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joshua T. Treudler
email: joshua@treudler.net
description: > # this means to ignore newlines until "baseurl:"
  Some text has to go here, but I have no idea. Welcome to my website.
baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://www.treudler.net/" # change this to the base hostname & protocol for your site

# Build settings
markdown: kramdown
# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
# permalink: /:categories/:year/:month/:day/:title.html
# none is equivalent to /:title.html
# https://jekyllrb.com/docs/permalinks
permalink: /:title.html

google_analytics: 

# jekyll-theme-simple-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
jekyll-theme-simple-blog:
  date_format: "%d.%m.%Y"

theme: # leave it empty

show_post_image_posts_list: true

header:
  image: 

# social
author:
  name: "Joshua Treudler"
  twitter: JoTreudler
  short_bio:
    en: I once founded Treudler Hosting. Now I'm working in the backend of multiple IT projects.
    de: Ich habe vor einiger Zeit Treudler Hosting gegründet. Heute bin ich tätig im Hintergrund von mehreren IT-Projekten.
  picture: assets/img/profile/jt.png


image: 

twitter:
  username: JoTreudler
#instagram_username:

#linkedin_username: lorepirri

site:
#facebook:
 # publisher_id: 1474191545979552
  #profile_id: 1474191545979552
  #app_id: 126080721296732
  #authors: [1474191545979552]
  #pixelcode: 1670622619859349
  twitter:
    username: JoTreudler

# gitlab on site
#gitlab:
 # owner_url: https://gitlab.com/Joshua2504

# github on site
github:
  owner_url: https://github.com/Joshua2504


# translation

t:
  en:
    latest-posts:  "My latest blog posts"
    read-more:  "read the full story"
    on-word: "on"
    contact: "Contact"
    contact-page: "contact-en.md"
    imprint: "Imprint"
    imprint-l: "imprint"
    imprint-page: "imprint-en.md"
    read-time: "min read"
    comments: "comments"
    go-to-home-page: "Go to the Home Page"
    months:
      january: "Jan"
      february: "Feb"
      march: "Mar"
      april: "Apr"
      may: "May"
      june: "Jun"
      july: "Jul"
      august: "Aug"
      september: "Sep"
      october: "Oct"
      november: "Nov"
      december : "Dec"
  de:
    latest-posts:  "Meine letzten Posts"
    read-more:  "den ganzen Post lesen"
    on-word: "zur"
    contact: "Kontakt"
    contact-page: "contact-de.md"
    imprint: "Impressum"
    imprint-l: "impressum"
    imprint-page: "imprint-de.md"
    read-time: "Minuten Lesezeit"
    comments: "Kommentare"
    go-to-home-page: "Gehe zur Hauptseite"
    months:
      january: "Jan"
      february: "Feb"
      march: "Mar"
      april: "Apr"
      may: "Mai"
      june: "Jun"
      july: "Jul"
      august: "Aug"
      september: "Sep"
      october: "Okt"
      november: "Nov"
      december : "Dez"

defaults:
  -
    scope:
      type: "posts"
    values:
      lang: "en"
      category: articles

plugin-dir: _plugins

